table Calendar
	lineageTag: 50d6038a-9242-4048-86b2-43db5926da66
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 90768482-827f-4eda-bff0-06fa269db25f
		summarizeBy: none
		sourceColumn: Date

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		lineageTag: a202ce4f-c3e6-41da-8ac9-56bfee99f564
		summarizeBy: none
		sourceColumn: Year

	column 'Month No'
		dataType: int64
		lineageTag: 01be93b8-8019-4a6b-a3e7-726204f20b97
		summarizeBy: none
		sourceColumn: Month No

	column Month-Year
		dataType: string
		lineageTag: c9cc2846-dda7-472c-8753-2c5d7350215e
		summarizeBy: none
		sourceColumn: Month-Year
		sortByColumn: 'Month Sort'

	column 'Month Sort'
		dataType: int64
		lineageTag: a0d420c2-53d1-46c1-95f8-7f3bdd2bf2a3
		summarizeBy: none
		sourceColumn: Month Sort

	column 'Week Start'
		dataType: dateTime
		formatString: Long Date
		lineageTag: da4a6cf6-d579-4112-9b2a-14fb1bcda92d
		summarizeBy: none
		sourceColumn: Week Start

		annotation UnderlyingDateTimeDataType = Date

	column 'Week Label'
		dataType: string
		lineageTag: 4bea9362-aa31-4619-9d84-0a3cd187ead6
		summarizeBy: none
		sourceColumn: Week Label

	partition Calendar = m
		mode: import
		source =
				let
				    StartDate = #date(2024, 1, 1),
				    EndDate = #date(2025, 12, 31),
				    Days = Duration.Days(EndDate - StartDate) + 1,
				    Dates = List.Dates(StartDate, Days, #duration(1, 0, 0, 0)),
				    Table0 = Table.FromList(Dates, Splitter.SplitByNothing(), {"Date"}),
				    Typed = Table.TransformColumnTypes(Table0, {{"Date", type date}}),
				    Added = Table.AddColumn(Typed, "Year", each Date.Year([Date]), Int64.Type),
				    Added2 = Table.AddColumn(Added, "Month No", each Date.Month([Date]), Int64.Type),
				    Added3 = Table.AddColumn(Added2, "Month-Year", each Date.ToText([Date], "MMM yy"), type text),
				    Added4 = Table.AddColumn(Added3, "Month Sort", each Date.Year([Date]) * 100 + Date.Month([Date]), Int64.Type),
				    Added5 = Table.AddColumn(Added4, "Week Start", each Date.StartOfWeek([Date], Day.Monday), type date),
				    Added6 = Table.AddColumn(Added5, "Week Label", each "W" & Text.From(Date.WeekOfYear([Date], Day.Monday)) & " " & Text.From(Date.Year([Date])), type text)
				in
				    Added6

