table CampaignSpend

	measure 'Total Spend' = SUM(CampaignSpend[Total Campaign Spend])
		formatString: \$#,0

	measure 'Total Media Cost' = SUM(CampaignSpend[Media Cost])
		formatString: \$#,0

	measure 'Total Production Cost' = SUM(CampaignSpend[Production Cost])
		formatString: \$#,0

	measure 'Total Agency Fee' = SUM(CampaignSpend[Calculated Agency Fee])
		formatString: \$#,0

	measure '% of Total Spend' = DIVIDE([Total Spend], CALCULATE([Total Spend], ALLSELECTED(CampaignSpend)))
		formatString: 0.0%

	measure 'Campaign Count' = DISTINCTCOUNT(CampaignSpend[Campaign Name])
		formatString: #,0

	measure 'Platform Count' = DISTINCTCOUNT(CampaignSpend[Marketing Platform])
		formatString: #,0

	/// Left (transparent) segment of the Campaign Schedule bar: days from the
	/// selected Date From to this campaign's start, clipped to 0. The Date slicer
	/// is on Calendar[Date]; harvesting MIN/MAX(Calendar[Date]) keeps the schedule
	/// anchored to the same Date From / Date To window as the Traffic Trend Analysis.
	/// Blank when the campaign does not overlap the window, so its bar drops off.
	measure 'Gantt Start Offset (Days)' = ```
			VAR WinFrom = MIN ( Calendar[Date] )
			VAR WinTo = MAX ( Calendar[Date] )
			VAR CampStart = MIN ( CampaignSpend[Start Date] )
			VAR CampEnd = MAX ( CampaignSpend[End Date] )
			VAR Overlaps = CampStart <= WinTo && CampEnd >= WinFrom
			VAR ClippedStart = IF ( CampStart < WinFrom, WinFrom, CampStart )
			RETURN IF ( Overlaps, DATEDIFF ( WinFrom, ClippedStart, DAY ) )
			```
		formatString: #,0

	/// Visible segment of the Campaign Schedule bar: the campaign's duration in days,
	/// clipped to the selected Date From / Date To window so the timeline lines up
	/// with the Traffic Trend Analysis. Blank (bar hidden) when the campaign does
	/// not overlap the window.
	measure 'Gantt Duration (Days)' = ```
			VAR WinFrom = MIN ( Calendar[Date] )
			VAR WinTo = MAX ( Calendar[Date] )
			VAR CampStart = MIN ( CampaignSpend[Start Date] )
			VAR CampEnd = MAX ( CampaignSpend[End Date] )
			VAR Overlaps = CampStart <= WinTo && CampEnd >= WinFrom
			VAR ClippedStart = IF ( CampStart < WinFrom, WinFrom, CampStart )
			VAR ClippedEnd = IF ( CampEnd > WinTo, WinTo, CampEnd )
			RETURN IF ( Overlaps, DATEDIFF ( ClippedStart, ClippedEnd, DAY ) + 1 )
			```
		formatString: #,0

	column 'Dept/Sch/Institute'
		dataType: string
		sourceColumn: Dept/Sch/Institute
		summarizeBy: none

	column 'Campaign ID'
		dataType: string
		sourceColumn: Campaign ID
		summarizeBy: none

	column 'Campaign Name'
		dataType: string
		sourceColumn: Campaign Name
		summarizeBy: none

	column 'Campaign Name for UTM'
		dataType: string
		sourceColumn: Campaign Name for UTM
		summarizeBy: none

	column 'Campaign Type'
		dataType: string
		sourceColumn: Campaign Type
		summarizeBy: none

	column 'Campaign Objective'
		dataType: string
		sourceColumn: Campaign Objective
		summarizeBy: none

	column 'Start Date'
		dataType: dateTime
		formatString: dd/mm/yyyy
		sourceColumn: Start Date
		summarizeBy: none

	column 'End Date'
		dataType: dateTime
		formatString: dd/mm/yyyy
		sourceColumn: End Date
		summarizeBy: none

	column 'Marketing Channel'
		dataType: string
		sourceColumn: Marketing Channel
		summarizeBy: none

	column 'Marketing Platform'
		dataType: string
		sourceColumn: Marketing Platform
		summarizeBy: none

	column Remarks
		dataType: string
		sourceColumn: Remarks
		summarizeBy: none

	column 'Agency Rate'
		dataType: double
		sourceColumn: Agency Rate
		summarizeBy: none

	column 'Media Cost'
		dataType: double
		sourceColumn: Media Cost
		summarizeBy: sum

	column 'Production Cost'
		dataType: double
		sourceColumn: Production Cost
		summarizeBy: sum

	column 'Calculated Agency Fee'
		dataType: double
		sourceColumn: Calculated Agency Fee
		summarizeBy: sum

	column 'Total Campaign Spend'
		dataType: double
		sourceColumn: Total Campaign Spend
		summarizeBy: sum

	column 'Campaign Duration (Days)' = DATEDIFF(CampaignSpend[Start Date], CampaignSpend[End Date], DAY)
		dataType: int64
		summarizeBy: none

	/// Single-line "Campaign — Platform" label so the Campaign Schedule bar chart
	/// can show BOTH the campaign and its Marketing Platform on one visible axis
	/// level (a bar-chart hierarchy would otherwise hide the platform behind drill-down).
	column 'Campaign & Platform' = CampaignSpend[Campaign Name] & "  —  " & CampaignSpend[Marketing Platform]
		dataType: string
		summarizeBy: none

	partition CampaignSpend = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(SourceFolder & "Final_Campaign_Spend_Data.csv"), [Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"Dept/Sch/Institute", type text}, {"Campaign ID", type text}, {"Campaign Name", type text}, {"Campaign Name for UTM", type text}, {"Campaign Type", type text}, {"Campaign Objective", type text}, {"Marketing Channel", type text}, {"Marketing Platform", type text}, {"Remarks", type text}, {"Agency Rate", type number}, {"Media Cost", type number}, {"Production Cost", type number}, {"Calculated Agency Fee", type number}, {"Total Campaign Spend", type number}}),
				    // Robustly parse Start/End Date whether they arrive as text datetimes
				    // ("2024-03-01 00:00:00") or as Excel serial numbers (e.g. 45445).
				    ToDate = (v) as nullable date => if v = null then null else if v is number then Date.From(#datetime(1899, 12, 30, 0, 0, 0) + #duration(v, 0, 0, 0)) else (let t = Text.Trim(Text.From(v)), n = try Number.FromText(t) otherwise null in if t = "" then null else if n <> null then Date.From(#datetime(1899, 12, 30, 0, 0, 0) + #duration(n, 0, 0, 0)) else try Date.From(DateTime.FromText(t)) otherwise Date.FromText(t)),
				    ParsedDates = Table.TransformColumns(Typed, {{"Start Date", ToDate, type date}, {"End Date", ToDate, type date}}),
				    Renamed = Table.ReplaceValue(ParsedDates, "Print", "Brochures", Replacer.ReplaceText, {"Marketing Platform"})
				in
				    Renamed
