table CampaignSpend

	measure 'Total Spend' = SUM(CampaignSpend[Total Campaign Spend])
		formatString: \$#,0

	measure 'Total Media Cost' = SUM(CampaignSpend[Media Cost])
		formatString: \$#,0

	measure 'Total Production Cost' = SUM(CampaignSpend[Production Cost])
		formatString: \$#,0

	measure 'Total Agency Fee' = SUM(CampaignSpend[Calculated Agency Fee])
		formatString: \$#,0

	measure '% of Total Spend' = DIVIDE([Total Spend], CALCULATE([Total Spend], ALLSELECTED(CampaignSpend)))
		formatString: 0.0%

	measure 'Campaign Count' = DISTINCTCOUNT(CampaignSpend[Campaign Name])
		formatString: #,0

	column 'Dept/Sch/Institute'
		dataType: string
		sourceColumn: Dept/Sch/Institute
		summarizeBy: none

	column 'Campaign ID'
		dataType: string
		sourceColumn: Campaign ID
		summarizeBy: none

	column 'Campaign Name'
		dataType: string
		sourceColumn: Campaign Name
		summarizeBy: none

	column 'Campaign Name for UTM'
		dataType: string
		sourceColumn: Campaign Name for UTM
		summarizeBy: none

	column 'Campaign Type'
		dataType: string
		sourceColumn: Campaign Type
		summarizeBy: none

	column 'Campaign Objective'
		dataType: string
		sourceColumn: Campaign Objective
		summarizeBy: none

	column 'Start Date'
		dataType: dateTime
		formatString: dd/mm/yyyy
		sourceColumn: Start Date
		summarizeBy: none

	column 'End Date'
		dataType: dateTime
		formatString: dd/mm/yyyy
		sourceColumn: End Date
		summarizeBy: none

	column 'Marketing Channel'
		dataType: string
		sourceColumn: Marketing Channel
		summarizeBy: none

	column 'Marketing Platform'
		dataType: string
		sourceColumn: Marketing Platform
		summarizeBy: none

	column Remarks
		dataType: string
		sourceColumn: Remarks
		summarizeBy: none

	column 'Agency Rate'
		dataType: double
		sourceColumn: Agency Rate
		summarizeBy: none

	column 'Media Cost'
		dataType: double
		sourceColumn: Media Cost
		summarizeBy: sum

	column 'Production Cost'
		dataType: double
		sourceColumn: Production Cost
		summarizeBy: sum

	column 'Calculated Agency Fee'
		dataType: double
		sourceColumn: Calculated Agency Fee
		summarizeBy: sum

	column 'Total Campaign Spend'
		dataType: double
		sourceColumn: Total Campaign Spend
		summarizeBy: sum

	column 'Campaign Duration (Days)' = DATEDIFF(CampaignSpend[Start Date], CampaignSpend[End Date], DAY)
		dataType: int64
		summarizeBy: none

	partition CampaignSpend = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(SourceFolder & "Final_Campaign_Spend_Data.csv"), [Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"Dept/Sch/Institute", type text}, {"Campaign ID", type text}, {"Campaign Name", type text}, {"Campaign Name for UTM", type text}, {"Campaign Type", type text}, {"Campaign Objective", type text}, {"Start Date", type datetime}, {"End Date", type datetime}, {"Marketing Channel", type text}, {"Marketing Platform", type text}, {"Remarks", type text}, {"Agency Rate", type number}, {"Media Cost", type number}, {"Production Cost", type number}, {"Calculated Agency Fee", type number}, {"Total Campaign Spend", type number}}),
				    AsDates = Table.TransformColumnTypes(Typed, {{"Start Date", type date}, {"End Date", type date}}),
				    Renamed = Table.ReplaceValue(AsDates, "Print", "Brochures", Replacer.ReplaceText, {"Marketing Platform"})
				in
				    Renamed
