table FactActualSpend

	column 'Campaign Name'
		dataType: string
		sourceColumn: Campaign Name
		summarizeBy: none

	column Spend
		dataType: double
		sourceColumn: Spend
		summarizeBy: sum

	column Impressions
		dataType: int64
		sourceColumn: Impressions
		summarizeBy: sum

	column Clicks
		dataType: int64
		sourceColumn: Clicks
		summarizeBy: sum

	column Platform
		dataType: string
		sourceColumn: Platform
		summarizeBy: none

	partition FactActualSpend = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(SourceFolder & "Fact_Actual_Spend.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"Campaign Name", type text}, {"Spend", type number}, {"Impressions", Int64.Type}, {"Clicks", Int64.Type}, {"Platform", type text}})
				in
				    Typed
