table FactActualSpend
	lineageTag: 23e187a5-adac-4aef-a125-cb162a19738e

	measure 'Total Impressions' = SUM(FactActualSpend[Impressions])
		formatString: #,0

	measure 'Total Clicks' = SUM(FactActualSpend[Clicks])
		formatString: #,0

	measure 'Total Actual Spend' = SUM(FactActualSpend[Spend])
		formatString: \$#,0

	/// Click-through rate = Clicks / Impressions
	measure CTR = DIVIDE([Total Clicks], [Total Impressions])
		formatString: 0.00%

	/// Cost per click = Spend / Clicks
	measure CPC = DIVIDE([Total Actual Spend], [Total Clicks])
		formatString: \$#,0.00

	/// Cost per thousand impressions = Spend / Impressions * 1000
	measure CPM = DIVIDE([Total Actual Spend], [Total Impressions]) * 1000
		formatString: \$#,0.00

	column 'Campaign Name'
		dataType: string
		lineageTag: 7b390396-d2e7-4b5e-86a8-ba9733267c61
		summarizeBy: none
		sourceColumn: Campaign Name

	column Spend
		dataType: double
		lineageTag: 7bf36437-163e-418c-b3ac-b077ec1b0a62
		summarizeBy: sum
		sourceColumn: Spend

	column Impressions
		dataType: int64
		lineageTag: 8f4406c0-7556-4a18-8fda-90cbb99731ca
		summarizeBy: sum
		sourceColumn: Impressions

	column Clicks
		dataType: int64
		lineageTag: e2879305-ee40-4047-b1bf-d25b9ba4d92c
		summarizeBy: sum
		sourceColumn: Clicks

	column Platform
		dataType: string
		lineageTag: 967f2679-f80a-4e29-b1fa-90ff028ed6f3
		summarizeBy: none
		sourceColumn: Platform

	/// Marketing objective parsed from the campaign-name text (3rd " - " segment,
	/// e.g. "NY2520 - CET B2C - Awareness - ..."). Rows without that pattern
	/// (e.g. YouTube targeting rows) fall back to "(Unspecified)".
	column 'Marketing Objective'
		dataType: string
		lineageTag: a7d1e0c2-4f3b-4a10-9c21-8e5b0d4f7a20
		summarizeBy: none
		sourceColumn: Marketing Objective

	partition FactActualSpend = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(SourceFolder & "Fact_Actual_Spend.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"Campaign Name", type text}, {"Spend", type number}, {"Impressions", Int64.Type}, {"Clicks", Int64.Type}, {"Platform", type text}}),
				    AddObjective = Table.AddColumn(Typed, "Marketing Objective", each let parts = Text.Split(Text.From([Campaign Name]), " - ") in if List.Count(parts) >= 3 then Text.Trim(parts{2}) else "(Unspecified)", type text)
				in
				    AddObjective


